apiVersion: v1
kind: Service
metadata:
  name: kube
  namespace: kube
spec:
  type: ClusterIP
  selector:
    app: kube
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
